### ISSUE TITLE
Icon no longer appears in Firefox

### ISSUE THREAD

**Issue by tinatenatean** [JeffreyATW/mbfc_icon#7]
After the last couple Firefox updates, I no longer see the media bias icon on any of the sites I'd seen it on before (e.g. CNN).  If I expand the three dotted icon, I see the MBFC app icon, but not the site's rating.  
![image](https://user-images.githubusercontent.com/37381483/68995074-c5af5300-0857-11ea-9927-d9e7c2003350.png)
![image](https://user-images.githubusercontent.com/37381483/68995095-f0011080-0857-11ea-8c17-e72ac77186fe.png)

**Comment by JeffreyATW** [comment]
Hi @tinatenatean - I can't reproduce this issue. The icon still shows up for me regularly. That said, it doesn't appear on CNN anymore - specifically because [this page](https://mediabiasfactcheck.com/cnn/) links to https://edition.cnn.com instead of https://cnn.com. That is something to take up with the staff of MBFC.

**Comment by grahamperrin** [comment]
I can't reproduce this, either. 

```text
grahamperrin@momh167-gjp4-8570p:~ % date ; uname -v
Fri 22 Nov 2019 19:24:25 GMT
FreeBSD 13.0-CURRENT #37 r354945: Thu Nov 21 19:11:47 GMT 2019     root@momh167-gjp4-8570p:/usr/obj/usr/src/amd64.amd64/sys/GENERIC-NODEBUG 
grahamperrin@momh167-gjp4-8570p:~ % pkg query '%o %v %R' firefox
www/firefox 70.0.1_3,1 FreeBSD
grahamperrin@momh167-gjp4-8570p:~ % 
```

https://edition.cnn.com/ is recognised. 

https://us.cnn.com/ is not recognised. I see what may be a minor cosmetic bug, I'll raise a separate issue.
